image: node:10

pipelines:
  default:
    - step:
        caches:
           - node
        script:
         - npm install
         - npm install -g @angular/cli
         - ng build --prod
         - ls -ltr
         - cd dist/admin
         - pipe: atlassian/aws-s3-deploy:0.2.4
           variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              ACL: "public-read"
              AWS_DEFAULT_REGION: 'ap-southeast-2'
              S3_BUCKET: 'days365admin'
              LOCAL_PATH: $(pwd)
          
